import { SectionWrapper } from "./SectionWrapper"

const MOCK_INSIGHTS = {
  topProblems: [
    {
      rank: 1,
      title: "Battery swap flow is severely degraded",
      detail:
        "FF-2841 (TypeError on null batteryLevel) spiked +262% this week and now affects 312 contractors. Amplitude confirms a 21% drop-off at the confirmation step. The QR timeout issue (FF-2901) compounds this — both errors target the same flow and neither has been resolved.",
      severity: "critical" as const,
    },
    {
      rank: 2,
      title: "Damage photo uploads are completely broken for large files",
      detail:
        "FF-3012 is new this week (441 events, 87 contractors). Slack shows damage collectors are resorting to WhatsApp workarounds. The 413 Payload Too Large error suggests no server-side size handling or client-side compression. Amplitude shows a 29% drop-off at the upload step.",
      severity: "high" as const,
    },
    {
      rank: 3,
      title: "Session timeouts are interrupting every contractor role",
      detail:
        "FF-2789 (AuthError token refresh) was resolved but caused 1,203 events last week. The Slack thread confirms tokens now expire after 2h instead of 8h. Even resolved, the root cause of the regression hasn't been documented.",
      severity: "medium" as const,
    },
  ],
  patterns: [
    "Battery Swap errors have been present for 3+ weeks (FF-2841 first seen Apr 14) — repeated without resolution.",
    "Rebalancing route errors (FF-2956) are stable week-over-week at ~600 events, suggesting it is accepted as background noise rather than actively prioritised.",
    "GPS failures in Guardian Patrol (FF-3045) consistently generate ~200 events/week. Correlates with Slack reports of City of London zone coverage issues.",
  ],
  actionPoints: [
    "Add a null check guard for batteryLevel in SwapConfirmation (FF-2841) — this is a one-line fix that unblocks 312 contractors immediately.",
    "Set a client-side image compression step before upload in DamageCollector, and raise the server limit to 20MB. Resolves FF-3012 and restores the damage reporting flow.",
    "Investigate why the session token TTL regressed from 8h to 2h post-deploy. Document the change and restore the expected value.",
    "Treat rebalancing route fetch failures (FF-2956) as P2 — it has been recurring for 2 weeks at high volume and appears to be normalised.",
  ],
}

const severityStyle = {
  critical: "border-red-800 bg-red-950/40",
  high: "border-orange-800 bg-orange-950/30",
  medium: "border-yellow-800 bg-yellow-950/20",
}

const severityBadge = {
  critical: "bg-red-900/60 text-red-300 border-red-800",
  high: "bg-orange-900/50 text-orange-300 border-orange-800",
  medium: "bg-yellow-900/40 text-yellow-300 border-yellow-800",
}

export function InsightsSection() {
  return (
    <SectionWrapper
      title="Insights — Week of Apr 21–27"
      subtitle="Generated by Claude · Connect ANTHROPIC_API_KEY to enable live analysis"
      badge="Mock data"
      badgeColor="slate"
    >
      <div className="rounded-lg border border-slate-700 bg-slate-800/50 px-4 py-3 mb-6 text-xs text-slate-400">
        <span className="text-slate-300 font-medium">Note:</span> These insights are static mock data.
        Once you add{" "}
        <code className="font-mono bg-slate-700 px-1 rounded">ANTHROPIC_API_KEY</code> to your{" "}
        <code className="font-mono bg-slate-700 px-1 rounded">.env</code>, this section will call
        Claude with live data from Sentry, Slack and Amplitude and generate real analysis.
      </div>

      <div className="mb-8">
        <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wide mb-3">
          Top 3 problems this week
        </h3>
        <div className="space-y-3">
          {MOCK_INSIGHTS.topProblems.map((p) => (
            <div key={p.rank} className={`rounded-lg border px-4 py-3 ${severityStyle[p.severity]}`}>
              <div className="flex items-center gap-2 mb-2">
                <span className="text-slate-500 font-mono text-xs">#{p.rank}</span>
                <span className="text-sm font-semibold text-slate-100">{p.title}</span>
                <span className={`ml-auto text-xs px-2 py-0.5 rounded border font-medium flex-shrink-0 ${severityBadge[p.severity]}`}>
                  {p.severity}
                </span>
              </div>
              <p className="text-xs text-slate-400 leading-relaxed">{p.detail}</p>
            </div>
          ))}
        </div>
      </div>

      <div className="mb-8">
        <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wide mb-3">
          Patterns vs. last week
        </h3>
        <ul className="space-y-2">
          {MOCK_INSIGHTS.patterns.map((p, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-slate-300">
              <span className="text-slate-600 mt-0.5 flex-shrink-0">→</span>
              {p}
            </li>
          ))}
        </ul>
      </div>

      <div>
        <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wide mb-3">
          Action points for the product designer
        </h3>
        <ol className="space-y-3">
          {MOCK_INSIGHTS.actionPoints.map((a, i) => (
            <li key={i} className="flex items-start gap-3">
              <span className="flex-shrink-0 h-5 w-5 rounded-full bg-violet-900/60 border border-violet-700 flex items-center justify-center text-xs text-violet-300 font-semibold">
                {i + 1}
              </span>
              <p className="text-sm text-slate-300 leading-relaxed">{a}</p>
            </li>
          ))}
        </ol>
      </div>
    </SectionWrapper>
  )
}
